### ISSUE TITLE
Widgets are not showing after latest update

### ISSUE THREAD

**Issue by PWHSoftware** [LearnPress/LearnPress#135]
"Featured Course" widget and other default LearnPress widgets are no longer present under the "Widgets" tab after the latest update.

Installed a fresh LearnPress install on two sites with the same result. The previous areas of my site containing said widgets are now blank.

EDIT: After further research, it looks as if this was intentional. Reintroduced functionality on my end.

**Comment by haihld58** [comment]
Hello PWHSoftware,

It’s due to latest version LP was removed some widget so it is not appeared now.
You can still use LearnPress Widget by change line 238 of file learnpress.php from:
/// add_action( 'widgets_init', array( $this, 'widgets_init' ) );
to:
add_action( 'widgets_init', array( $this, 'widgets_init' ) );
