### ISSUE TITLE
Multilanguage Profile Page

### ISSUE THREAD

**Issue by pisacode** [LearnPress/learnpress#317]
Hi,

I am using wmpl to translate pages. However I can't set profile page url for two languages. It only shows the profile page on only one language. Is anyone having the same problem?

Many thanks

**Comment by monaxide** [comment]
I have used Polylang. Exactly same problem. It's seems to be a problem in LearnPress, it can't create a profile page and payment page.

**Comment by u451f** [comment]
The profile page needs to exist in both languages - you need to create it. In the settings, only activate the profile page of your main language. It works. However, what does not work is the sublinks on the profile page, they exist in the translated language, but the links are always pointing to the main language. It might be an issue with LP, instead of Polylang though.
