### ISSUE TITLE
lessons or quizs not display in edit course page

### ISSUE THREAD

**Issue by Dguesdon** [LearnPress/learnpress#530]
the lessons and quizs under the chapters on the course editing page cannot be displayed.
the questions are display on the quizs editing page.
But when i tried the quiz in the course it says the course doesn't exist or haven't quiz.
When I check mysql, lessons and quizs are associated with the course, but they are not displayed.

I cloused all plugins

wordpress version: 6.0.3
learnpress version: 4.1.7.2

I tried to create new course with new lessons and quizs but there are the sames maters.
I tried to update learnpress in the last version ( 4.1.7.3.2) and it doesn't change anything.

**Comment by tungnxt89** [comment]
Hi seniorcat,

Yes, you need to fix it, it will run right. Can you send us the image error?

Thanks.

**Comment by tungnxt89** [comment]
Hi seniorcat,

Yes, "_lp_info_extra_fast_query" makes the query super fast; it doesn't need the query to join many tables to get the list.
WP's default remote get function runs normally most of the time, but it does not always because the SSL configuration is incorrect or something else. LP needs to use that for running some background functions. Curl is used before wp_remote_get, but some servers disable it by default. So currently, we don't have a choice for another solution. If you know, please contribute to us.

Thanks so much.
